version: 2.1  # Define the CircleCI configuration version

# Executors define the environment in which the jobs run.
executors:
  node-executor:
    docker:
      - image: circleci/node:14  # Official Node.js Docker image
    working_directory: ~/my-node-app  # Define the working directory

# Define individual jobs that do specific tasks.
jobs:
  # Job 1: Install dependencies
  install_dependencies:
    executor: node-executor  # Use the node-executor defined above
    steps:
      - checkout  # Step to clone the repository
      - run:
          name: Install Node.js Dependencies
          command: npm install  # Command to install Node.js dependencies

  # Job 2: Run tests
  run_tests:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Run Tests
          command: npm test  # Add your test command here (change it as per your project)
  
  # Job 3: Build (if applicable for your project)
  build_application:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Build Application
          command: npm run build  # Only needed if your project requires a build step (optional)

  # Job 4: Deploy the application (you can customize it for your deployment strategy)
  deploy_application:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Deploy Application
          command: echo "Deploying application..."  # Replace with actual deployment commands

# Workflows define the order in which jobs are executed.
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - install_dependencies  # Run this job first
      - run_tests:  # Run tests after dependencies are installed
          requires:
            - install_dependencies
      - build_application:  # Build the app if tests pass
          requires:
            - run_tests
      - deploy_application:  # Deploy the app if build succeeds
          requires:
            - build_application
