version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/node:16

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build the Docker image
          command: docker build -t circleci-nodejs-sample .
      - run:
          name: Run the container
          command: docker run -d -p 3000:3000 circleci-nodejs-sample

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
